package com.athar.app.ui.corner

/** Surah metadata (Madinah mushaf order, standard ayah counts). */
data class SurahMeta(
    val number: Int,
    val arabicName: String,
    val englishName: String,
    val ayahs: Int
)

/**
 * Full Arabic text for the surahs readable in this beta.
 * Key = surah number. Others show a "coming soon" note.
 * Texts follow the Madinah mushaf (Uthmani) wording.
 */
val readableSurahText: Map<Int, String> = mapOf(
    1 to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ﴿١﴾ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ﴿٢﴾ الرَّحْمَٰنِ الرَّحِيمِ ﴿٣﴾ مَالِكِ يَوْمِ الدِّينِ ﴿٤﴾ إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ﴿٥﴾ اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ﴿٦﴾ صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ ﴿٧﴾",
    103 to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ وَالْعَصْرِ ﴿١﴾ إِنَّ الْإِنسَانَ لَفِي خُسْرٍ ﴿٢﴾ إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ ﴿٣﴾",
    108 to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ ﴿١﴾ فَصَلِّ لِرَبِّكَ وَانْحَرْ ﴿٢﴾ إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ ﴿٣﴾",
    110 to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ ﴿١﴾ وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا ﴿٢﴾ فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ ۚ إِنَّهُ كَانَ تَوَّابًا ﴿٣﴾",
    112 to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ ﴿١﴾ اللَّهُ الصَّمَدُ ﴿٢﴾ لَمْ يَلِدْ وَلَمْ يُولَدْ ﴿٣﴾ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ ﴿٤﴾",
    113 to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ﴿١﴾ مِن شَرِّ مَا خَلَقَ ﴿٢﴾ وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ ﴿٣﴾ وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ ﴿٤﴾ وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ ﴿٥﴾",
    114 to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ ﴿١﴾ مَلِكِ النَّاسِ ﴿٢﴾ إِلَٰهِ النَّاسِ ﴿٣﴾ مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ ﴿٤﴾ الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ ﴿٥﴾ مِنَ الْجِنَّةِ وَالنَّاسِ ﴿٦﴾"
)

val allSurahs: List<SurahMeta> = listOf(
    SurahMeta(1, "الفاتحة", "Al-Fatiha", 7),
    SurahMeta(2, "البقرة", "Al-Baqarah", 286),
    SurahMeta(3, "آل عمران", "Aal-Imran", 200),
    SurahMeta(4, "النساء", "An-Nisa", 176),
    SurahMeta(5, "المائدة", "Al-Ma'idah", 120),
    SurahMeta(6, "الأنعام", "Al-An'am", 165),
    SurahMeta(7, "الأعراف", "Al-A'raf", 206),
    SurahMeta(8, "الأنفال", "Al-Anfal", 75),
    SurahMeta(9, "التوبة", "At-Tawbah", 129),
    SurahMeta(10, "يونس", "Yunus", 109),
    SurahMeta(11, "هود", "Hud", 123),
    SurahMeta(12, "يوسف", "Yusuf", 111),
    SurahMeta(13, "الرعد", "Ar-Ra'd", 43),
    SurahMeta(14, "إبراهيم", "Ibrahim", 52),
    SurahMeta(15, "الحجر", "Al-Hijr", 99),
    SurahMeta(16, "النحل", "An-Nahl", 128),
    SurahMeta(17, "الإسراء", "Al-Isra", 111),
    SurahMeta(18, "الكهف", "Al-Kahf", 110),
    SurahMeta(19, "مريم", "Maryam", 98),
    SurahMeta(20, "طه", "Taha", 135),
    SurahMeta(21, "الأنبياء", "Al-Anbiya", 112),
    SurahMeta(22, "الحج", "Al-Hajj", 78),
    SurahMeta(23, "المؤمنون", "Al-Mu'minun", 118),
    SurahMeta(24, "النور", "An-Nur", 64),
    SurahMeta(25, "الفرقان", "Al-Furqan", 77),
    SurahMeta(26, "الشعراء", "Ash-Shu'ara", 227),
    SurahMeta(27, "النمل", "An-Naml", 93),
    SurahMeta(28, "القصص", "Al-Qasas", 88),
    SurahMeta(29, "العنكبوت", "Al-Ankabut", 69),
    SurahMeta(30, "الروم", "Ar-Rum", 60),
    SurahMeta(31, "لقمان", "Luqman", 34),
    SurahMeta(32, "السجدة", "As-Sajdah", 30),
    SurahMeta(33, "الأحزاب", "Al-Ahzab", 73),
    SurahMeta(34, "سبأ", "Saba", 54),
    SurahMeta(35, "فاطر", "Fatir", 45),
    SurahMeta(36, "يس", "Ya-Sin", 83),
    SurahMeta(37, "الصافات", "As-Saffat", 182),
    SurahMeta(38, "ص", "Sad", 88),
    SurahMeta(39, "الزمر", "Az-Zumar", 75),
    SurahMeta(40, "غافر", "Ghafir", 85),
    SurahMeta(41, "فصلت", "Fussilat", 54),
    SurahMeta(42, "الشورى", "Ash-Shura", 53),
    SurahMeta(43, "الزخرف", "Az-Zukhruf", 89),
    SurahMeta(44, "الدخان", "Ad-Dukhan", 59),
    SurahMeta(45, "الجاثية", "Al-Jathiyah", 37),
    SurahMeta(46, "الأحقاف", "Al-Ahqaf", 35),
    SurahMeta(47, "محمد", "Muhammad", 38),
    SurahMeta(48, "الفتح", "Al-Fath", 29),
    SurahMeta(49, "الحجرات", "Al-Hujurat", 18),
    SurahMeta(50, "ق", "Qaf", 45),
    SurahMeta(51, "الذاريات", "Adh-Dhariyat", 60),
    SurahMeta(52, "الطور", "At-Tur", 49),
    SurahMeta(53, "النجم", "An-Najm", 62),
    SurahMeta(54, "القمر", "Al-Qamar", 55),
    SurahMeta(55, "الرحمن", "Ar-Rahman", 78),
    SurahMeta(56, "الواقعة", "Al-Waqi'ah", 96),
    SurahMeta(57, "الحديد", "Al-Hadid", 29),
    SurahMeta(58, "المجادلة", "Al-Mujadila", 22),
    SurahMeta(59, "الحشر", "Al-Hashr", 24),
    SurahMeta(60, "الممتحنة", "Al-Mumtahanah", 13),
    SurahMeta(61, "الصف", "As-Saff", 14),
    SurahMeta(62, "الجمعة", "Al-Jumu'ah", 11),
    SurahMeta(63, "المنافقون", "Al-Munafiqun", 11),
    SurahMeta(64, "التغابن", "At-Taghabun", 18),
    SurahMeta(65, "الطلاق", "At-Talaq", 12),
    SurahMeta(66, "التحريم", "At-Tahrim", 12),
    SurahMeta(67, "الملك", "Al-Mulk", 30),
    SurahMeta(68, "القلم", "Al-Qalam", 52),
    SurahMeta(69, "الحاقة", "Al-Haqqah", 52),
    SurahMeta(70, "المعارج", "Al-Ma'arij", 44),
    SurahMeta(71, "نوح", "Nuh", 28),
    SurahMeta(72, "الجن", "Al-Jinn", 28),
    SurahMeta(73, "المزمل", "Al-Muzzammil", 20),
    SurahMeta(74, "المدثر", "Al-Muddaththir", 56),
    SurahMeta(75, "القيامة", "Al-Qiyamah", 40),
    SurahMeta(76, "الإنسان", "Al-Insan", 31),
    SurahMeta(77, "المرسلات", "Al-Mursalat", 50),
    SurahMeta(78, "النبأ", "An-Naba", 40),
    SurahMeta(79, "النازعات", "An-Nazi'at", 46),
    SurahMeta(80, "عبس", "Abasa", 42),
    SurahMeta(81, "التكوير", "At-Takwir", 29),
    SurahMeta(82, "الانفطار", "Al-Infitar", 19),
    SurahMeta(83, "المطففين", "Al-Mutaffifin", 36),
    SurahMeta(84, "الانشقاق", "Al-Inshiqaq", 25),
    SurahMeta(85, "البروج", "Al-Buruj", 22),
    SurahMeta(86, "الطارق", "At-Tariq", 17),
    SurahMeta(87, "الأعلى", "Al-A'la", 19),
    SurahMeta(88, "الغاشية", "Al-Ghashiyah", 26),
    SurahMeta(89, "الفجر", "Al-Fajr", 30),
    SurahMeta(90, "البلد", "Al-Balad", 20),
    SurahMeta(91, "الشمس", "Ash-Shams", 15),
    SurahMeta(92, "الليل", "Al-Layl", 21),
    SurahMeta(93, "الضحى", "Ad-Duha", 11),
    SurahMeta(94, "الشرح", "Ash-Sharh", 8),
    SurahMeta(95, "التين", "At-Tin", 8),
    SurahMeta(96, "العلق", "Al-Alaq", 19),
    SurahMeta(97, "القدر", "Al-Qadr", 5),
    SurahMeta(98, "البينة", "Al-Bayyinah", 8),
    SurahMeta(99, "الزلزلة", "Az-Zalzalah", 8),
    SurahMeta(100, "العاديات", "Al-Adiyat", 11),
    SurahMeta(101, "القارعة", "Al-Qari'ah", 11),
    SurahMeta(102, "التكاثر", "At-Takathur", 8),
    SurahMeta(103, "العصر", "Al-Asr", 3),
    SurahMeta(104, "الهمزة", "Al-Humazah", 9),
    SurahMeta(105, "الفيل", "Al-Fil", 5),
    SurahMeta(106, "قريش", "Quraysh", 4),
    SurahMeta(107, "الماعون", "Al-Ma'un", 7),
    SurahMeta(108, "الكوثر", "Al-Kawthar", 3),
    SurahMeta(109, "الكافرون", "Al-Kafirun", 6),
    SurahMeta(110, "النصر", "An-Nasr", 3),
    SurahMeta(111, "المسد", "Al-Masad", 5),
    SurahMeta(112, "الإخلاص", "Al-Ikhlas", 4),
    SurahMeta(113, "الفلق", "Al-Falaq", 5),
    SurahMeta(114, "الناس", "An-Nas", 6)
)
