package com.athar.app.ui.corner

enum class RevelationType(val arabicLabel: String, val englishLabel: String) {
    MECCAN("مكية", "Meccan"),
    MEDINAN("مدنية", "Medinan")
}

/** Surah metadata (Madinah mushaf order, canonical numbering, juz, pages, revelation place). */
data class SurahMeta(
    val number: Int,
    val arabicName: String,
    val englishName: String,
    val englishTranslation: String,
    val ayahs: Int,
    val juz: Int,
    val revelationType: RevelationType,
    val page: Int
)

/** Juz metadata (the 30 chapters / parts of the Holy Quran). */
data class JuzMeta(
    val number: Int,
    val arabicName: String,
    val englishName: String,
    val startSurahNumber: Int,
    val startAyah: Int,
    val startPage: Int
)

val allJuz: List<JuzMeta> = listOf(
    JuzMeta(1, "الجزء الأول (الم)", "Juz 1", 1, 1, 1),
    JuzMeta(2, "الجزء الثاني (سيقول)", "Juz 2", 2, 142, 22),
    JuzMeta(3, "الجزء الثالث (تلك الرسل)", "Juz 3", 2, 253, 42),
    JuzMeta(4, "الجزء الرابع (لن تنالوا)", "Juz 4", 3, 93, 62),
    JuzMeta(5, "الجزء الخامس (والمحصنات)", "Juz 5", 4, 24, 82),
    JuzMeta(6, "الجزء السادس (لا يحب الله)", "Juz 6", 4, 148, 102),
    JuzMeta(7, "الجزء السابع (وإذا سمعوا)", "Juz 7", 5, 82, 121),
    JuzMeta(8, "الجزء الثامن (ولو أننا)", "Juz 8", 6, 111, 142),
    JuzMeta(9, "الجزء التاسع (قال الملأ)", "Juz 9", 7, 88, 162),
    JuzMeta(10, "الجزء العاشر (واعلموا)", "Juz 10", 8, 41, 182),
    JuzMeta(11, "الجزء الحادي عشر (يعتذرون)", "Juz 11", 9, 93, 201),
    JuzMeta(12, "الجزء الثاني عشر (وما من دابة)", "Juz 12", 11, 6, 222),
    JuzMeta(13, "الجزء الثالث عشر (وما أبرئ)", "Juz 13", 12, 53, 242),
    JuzMeta(14, "الجزء الرابع عشر (ربما)", "Juz 14", 15, 1, 262),
    JuzMeta(15, "الجزء الخامس عشر (سبحان الذي)", "Juz 15", 17, 1, 282),
    JuzMeta(16, "الجزء السادس عشر (قال ألم)", "Juz 16", 18, 75, 302),
    JuzMeta(17, "الجزء السابع عشر (اقترب)", "Juz 17", 21, 1, 322),
    JuzMeta(18, "الجزء الثامن عشر (قد أفلح)", "Juz 18", 23, 1, 342),
    JuzMeta(19, "الجزء التاسع عشر (وقال الذين)", "Juz 19", 25, 21, 362),
    JuzMeta(20, "الجزء العشرون (أمن خلق)", "Juz 20", 27, 56, 382),
    JuzMeta(21, "الجزء الحادي والعشرون (اتل ما أوحي)", "Juz 21", 29, 46, 402),
    JuzMeta(22, "الجزء الثاني والعشرون (ومن يقنت)", "Juz 22", 33, 31, 422),
    JuzMeta(23, "الجزء الثالث والعشرون (وما أنزلنا)", "Juz 23", 36, 28, 442),
    JuzMeta(24, "الجزء الرابع والعشرون (فمن أظلم)", "Juz 24", 39, 32, 462),
    JuzMeta(25, "الجزء الخامس والعشرون (إليه يرد)", "Juz 25", 41, 47, 482),
    JuzMeta(26, "الجزء السادس والعشرون (حم)", "Juz 26", 46, 1, 502),
    JuzMeta(27, "الجزء السابع والعشرون (قال فما خطبكم)", "Juz 27", 51, 31, 522),
    JuzMeta(28, "الجزء الثامن والعشرون (قد سمع الله)", "Juz 28", 58, 1, 542),
    JuzMeta(29, "الجزء التاسع والعشرون (تبارك الذي)", "Juz 29", 67, 1, 562),
    JuzMeta(30, "الجزء الثلاثون (عم يتساءلون)", "Juz 30", 78, 1, 582)
)

val allSurahs: List<SurahMeta> = listOf(
    SurahMeta(1, "الفاتحة", "Al-Fatihah", "The Opening", 7, 1, RevelationType.MECCAN, 1),
    SurahMeta(2, "البقرة", "Al-Baqarah", "The Cow", 286, 1, RevelationType.MEDINAN, 2),
    SurahMeta(3, "آل عمران", "Ali 'Imran", "Family of Imran", 200, 3, RevelationType.MEDINAN, 50),
    SurahMeta(4, "النساء", "An-Nisa", "The Women", 176, 4, RevelationType.MEDINAN, 77),
    SurahMeta(5, "المائدة", "Al-Ma'idah", "The Table Spread", 120, 6, RevelationType.MEDINAN, 106),
    SurahMeta(6, "الأنعام", "Al-An'am", "The Cattle", 165, 7, RevelationType.MECCAN, 128),
    SurahMeta(7, "الأعراف", "Al-A'raf", "The Heights", 206, 8, RevelationType.MECCAN, 151),
    SurahMeta(8, "الأنفال", "Al-Anfal", "The Spoils of War", 75, 9, RevelationType.MEDINAN, 177),
    SurahMeta(9, "التوبة", "At-Tawbah", "The Repentance", 129, 10, RevelationType.MEDINAN, 187),
    SurahMeta(10, "يونس", "Yunus", "Jonah", 109, 11, RevelationType.MECCAN, 208),
    SurahMeta(11, "هود", "Hud", "Hud", 123, 11, RevelationType.MECCAN, 221),
    SurahMeta(12, "يوسف", "Yusuf", "Joseph", 111, 12, RevelationType.MECCAN, 235),
    SurahMeta(13, "الرعد", "Ar-Ra'd", "The Thunder", 43, 13, RevelationType.MEDINAN, 249),
    SurahMeta(14, "إبراهيم", "Ibrahim", "Abraham", 52, 13, RevelationType.MECCAN, 255),
    SurahMeta(15, "الحجر", "Al-Hijr", "The Rocky Tract", 99, 14, RevelationType.MECCAN, 262),
    SurahMeta(16, "النحل", "An-Nahl", "The Bee", 128, 14, RevelationType.MECCAN, 267),
    SurahMeta(17, "الإسراء", "Al-Isra", "The Night Journey", 111, 15, RevelationType.MECCAN, 282),
    SurahMeta(18, "الكهف", "Al-Kahf", "The Cave", 110, 15, RevelationType.MECCAN, 293),
    SurahMeta(19, "مريم", "Maryam", "Mary", 98, 16, RevelationType.MECCAN, 305),
    SurahMeta(20, "طه", "Taha", "Ta-Ha", 135, 16, RevelationType.MECCAN, 312),
    SurahMeta(21, "الأنبياء", "Al-Anbiya", "The Prophets", 112, 17, RevelationType.MECCAN, 322),
    SurahMeta(22, "الحج", "Al-Hajj", "The Pilgrimage", 78, 17, RevelationType.MEDINAN, 332),
    SurahMeta(23, "المؤمنون", "Al-Mu'minun", "The Believers", 118, 18, RevelationType.MECCAN, 342),
    SurahMeta(24, "النور", "An-Nur", "The Light", 64, 18, RevelationType.MEDINAN, 350),
    SurahMeta(25, "الفرقان", "Al-Furqan", "The Criterion", 77, 18, RevelationType.MECCAN, 359),
    SurahMeta(26, "الشعراء", "Ash-Shu'ara", "The Poets", 227, 19, RevelationType.MECCAN, 367),
    SurahMeta(27, "النمل", "An-Naml", "The Ant", 93, 19, RevelationType.MECCAN, 377),
    SurahMeta(28, "القصص", "Al-Qasas", "The Stories", 88, 20, RevelationType.MECCAN, 385),
    SurahMeta(29, "العنكبوت", "Al-'Ankabut", "The Spider", 69, 20, RevelationType.MECCAN, 396),
    SurahMeta(30, "الروم", "Ar-Rum", "The Romans", 60, 21, RevelationType.MECCAN, 404),
    SurahMeta(31, "لقمان", "Luqman", "Luqman", 34, 21, RevelationType.MECCAN, 411),
    SurahMeta(32, "السجدة", "As-Sajdah", "The Prostration", 30, 21, RevelationType.MECCAN, 415),
    SurahMeta(33, "الأحزاب", "Al-Ahzab", "The Combined Forces", 73, 21, RevelationType.MEDINAN, 418),
    SurahMeta(34, "سبأ", "Saba", "Sheba", 54, 22, RevelationType.MECCAN, 428),
    SurahMeta(35, "فاطر", "Fatir", "Originator", 45, 22, RevelationType.MECCAN, 434),
    SurahMeta(36, "يس", "Ya-Sin", "Ya Sin", 83, 22, RevelationType.MECCAN, 440),
    SurahMeta(37, "الصافات", "As-Saffat", "Those who set the Ranks", 182, 23, RevelationType.MECCAN, 446),
    SurahMeta(38, "ص", "Sad", "The Letter Saad", 88, 23, RevelationType.MECCAN, 453),
    SurahMeta(39, "الزمر", "Az-Zumar", "The Troops", 75, 23, RevelationType.MECCAN, 458),
    SurahMeta(40, "غافر", "Ghafir", "The Forgiver", 85, 24, RevelationType.MECCAN, 467),
    SurahMeta(41, "فصلت", "Fussilat", "Explained in Detail", 54, 24, RevelationType.MECCAN, 477),
    SurahMeta(42, "الشورى", "Ash-Shuraa", "The Consultation", 53, 25, RevelationType.MECCAN, 483),
    SurahMeta(43, "الزخرف", "Az-Zukhruf", "The Ornaments of Gold", 89, 25, RevelationType.MECCAN, 489),
    SurahMeta(44, "الدخان", "Ad-Dukhan", "The Smoke", 59, 25, RevelationType.MECCAN, 496),
    SurahMeta(45, "الجاثية", "Al-Jathiyah", "The Crouching", 37, 25, RevelationType.MECCAN, 499),
    SurahMeta(46, "الأحقاف", "Al-Ahqaf", "The Wind-Curved Sandhills", 35, 26, RevelationType.MECCAN, 502),
    SurahMeta(47, "محمد", "Muhammad", "Muhammad", 38, 26, RevelationType.MEDINAN, 507),
    SurahMeta(48, "الفتح", "Al-Fath", "The Victory", 29, 26, RevelationType.MEDINAN, 511),
    SurahMeta(49, "الحجرات", "Al-Hujurat", "The Rooms", 18, 26, RevelationType.MEDINAN, 515),
    SurahMeta(50, "ق", "Qaf", "The Letter Qaf", 45, 26, RevelationType.MECCAN, 518),
    SurahMeta(51, "الذاريات", "Adh-Dhariyat", "The Winnowing Winds", 60, 26, RevelationType.MECCAN, 520),
    SurahMeta(52, "الطور", "At-Tur", "The Mount", 49, 27, RevelationType.MECCAN, 523),
    SurahMeta(53, "النجم", "An-Najm", "The Star", 62, 27, RevelationType.MECCAN, 526),
    SurahMeta(54, "القمر", "Al-Qamar", "The Moon", 55, 27, RevelationType.MECCAN, 528),
    SurahMeta(55, "الرحمن", "Ar-Rahman", "The Beneficent", 78, 27, RevelationType.MEDINAN, 531),
    SurahMeta(56, "الواقعة", "Al-Waqi'ah", "The Inevitable", 96, 27, RevelationType.MECCAN, 534),
    SurahMeta(57, "الحديد", "Al-Hadid", "The Iron", 29, 27, RevelationType.MEDINAN, 537),
    SurahMeta(58, "المجادلة", "Al-Mujadila", "The Pleading Woman", 22, 28, RevelationType.MEDINAN, 542),
    SurahMeta(59, "الحشر", "Al-Hashr", "The Exile", 24, 28, RevelationType.MEDINAN, 545),
    SurahMeta(60, "الممتحنة", "Al-Mumtahanah", "She that is to be examined", 13, 28, RevelationType.MEDINAN, 549),
    SurahMeta(61, "الصف", "As-Saf", "The Ranks", 14, 28, RevelationType.MEDINAN, 551),
    SurahMeta(62, "الجمعة", "Al-Jumu'ah", "The Congregation", 11, 28, RevelationType.MEDINAN, 553),
    SurahMeta(63, "المنافقون", "Al-Munafiqun", "The Hypocrites", 11, 28, RevelationType.MEDINAN, 554),
    SurahMeta(64, "التغابن", "At-Taghabun", "The Mutual Disillusion", 18, 28, RevelationType.MEDINAN, 556),
    SurahMeta(65, "الطلاق", "At-Talaq", "The Divorce", 12, 28, RevelationType.MEDINAN, 558),
    SurahMeta(66, "التحريم", "At-Tahrim", "The Prohibition", 12, 28, RevelationType.MEDINAN, 560),
    SurahMeta(67, "الملك", "Al-Mulk", "The Sovereignty", 30, 29, RevelationType.MECCAN, 562),
    SurahMeta(68, "القلم", "Al-Qalam", "The Pen", 52, 29, RevelationType.MECCAN, 564),
    SurahMeta(69, "الحاقة", "Al-Haqqah", "The Reality", 52, 29, RevelationType.MECCAN, 566),
    SurahMeta(70, "المعارج", "Al-Ma'arij", "The Ascending Stairways", 44, 29, RevelationType.MECCAN, 568),
    SurahMeta(71, "نوح", "Nuh", "Noah", 28, 29, RevelationType.MECCAN, 570),
    SurahMeta(72, "الجن", "Al-Jinn", "The Jinn", 28, 29, RevelationType.MECCAN, 572),
    SurahMeta(73, "المزمل", "Al-Muzzammil", "The Enshrouded One", 20, 29, RevelationType.MECCAN, 574),
    SurahMeta(74, "المدثر", "Al-Muddaththir", "The Cloaked One", 56, 29, RevelationType.MECCAN, 575),
    SurahMeta(75, "القيامة", "Al-Qiyamah", "The Resurrection", 40, 29, RevelationType.MECCAN, 577),
    SurahMeta(76, "الإنسان", "Al-Insan", "The Man", 31, 29, RevelationType.MEDINAN, 578),
    SurahMeta(77, "المرسلات", "Al-Mursalat", "The Emissaries", 50, 29, RevelationType.MECCAN, 580),
    SurahMeta(78, "النبأ", "An-Naba", "The Tidings", 40, 30, RevelationType.MECCAN, 582),
    SurahMeta(79, "النازعات", "An-Nazi'at", "Those who drag forth", 46, 30, RevelationType.MECCAN, 583),
    SurahMeta(80, "عبس", "'Abasa", "He Frowned", 42, 30, RevelationType.MECCAN, 585),
    SurahMeta(81, "التكوير", "At-Takwir", "The Overthrowing", 29, 30, RevelationType.MECCAN, 586),
    SurahMeta(82, "الانفطار", "Al-Infitar", "The Cleaving", 19, 30, RevelationType.MECCAN, 587),
    SurahMeta(83, "المطففين", "Al-Mutaffifin", "The Defrauding", 36, 30, RevelationType.MECCAN, 587),
    SurahMeta(84, "الانشقاق", "Al-Inshiqaq", "The Splitting Open", 25, 30, RevelationType.MECCAN, 589),
    SurahMeta(85, "البروج", "Al-Buruj", "The Mansions of the Stars", 22, 30, RevelationType.MECCAN, 590),
    SurahMeta(86, "الطارق", "At-Tariq", "The Morning Star", 17, 30, RevelationType.MECCAN, 591),
    SurahMeta(87, "الأعلى", "Al-A'la", "The Most High", 19, 30, RevelationType.MECCAN, 591),
    SurahMeta(88, "الغاشية", "Al-Ghashiyah", "The Overwhelming", 26, 30, RevelationType.MECCAN, 592),
    SurahMeta(89, "الفجر", "Al-Fajr", "The Dawn", 30, 30, RevelationType.MECCAN, 593),
    SurahMeta(90, "البلد", "Al-Balad", "The City", 20, 30, RevelationType.MECCAN, 594),
    SurahMeta(91, "الشمس", "Ash-Shams", "The Sun", 15, 30, RevelationType.MECCAN, 595),
    SurahMeta(92, "الليل", "Al-Layl", "The Night", 21, 30, RevelationType.MECCAN, 595),
    SurahMeta(93, "الضحى", "Ad-Duhaa", "The Morning Hours", 11, 30, RevelationType.MECCAN, 596),
    SurahMeta(94, "الشرح", "Ash-Sharh", "The Relief", 8, 30, RevelationType.MECCAN, 596),
    SurahMeta(95, "التين", "At-Tin", "The Fig", 8, 30, RevelationType.MECCAN, 597),
    SurahMeta(96, "العلق", "Al-'Alaq", "The Clot", 19, 30, RevelationType.MECCAN, 597),
    SurahMeta(97, "القدر", "Al-Qadr", "The Power", 5, 30, RevelationType.MECCAN, 598),
    SurahMeta(98, "البينة", "Al-Bayyinah", "The Clear Proof", 8, 30, RevelationType.MEDINAN, 598),
    SurahMeta(99, "الزلزلة", "Az-Zalzalah", "The Earthquake", 8, 30, RevelationType.MEDINAN, 599),
    SurahMeta(100, "العاديات", "Al-'Adiyat", "The Courser", 11, 30, RevelationType.MECCAN, 599),
    SurahMeta(101, "القارعة", "Al-Qari'ah", "The Calamity", 11, 30, RevelationType.MECCAN, 600),
    SurahMeta(102, "التكاثر", "At-Takathur", "The Rivalry in world increase", 8, 30, RevelationType.MECCAN, 600),
    SurahMeta(103, "العصر", "Al-'Asr", "The Declining Day", 3, 30, RevelationType.MECCAN, 601),
    SurahMeta(104, "الهمزة", "Al-Humazah", "The Traducer", 9, 30, RevelationType.MECCAN, 601),
    SurahMeta(105, "الفيل", "Al-Fil", "The Elephant", 5, 30, RevelationType.MECCAN, 601),
    SurahMeta(106, "قريش", "Quraysh", "Quraysh", 4, 30, RevelationType.MECCAN, 602),
    SurahMeta(107, "الماعون", "Al-Ma'un", "The Small Kindness", 7, 30, RevelationType.MECCAN, 602),
    SurahMeta(108, "الكوثر", "Al-Kawthar", "The Abundance", 3, 30, RevelationType.MECCAN, 602),
    SurahMeta(109, "الكافرون", "Al-Kafirun", "The Disbelievers", 6, 30, RevelationType.MECCAN, 603),
    SurahMeta(110, "النصر", "An-Nasr", "The Divine Support", 3, 30, RevelationType.MEDINAN, 603),
    SurahMeta(111, "المسد", "Al-Masad", "The Palm Fiber", 5, 30, RevelationType.MECCAN, 603),
    SurahMeta(112, "الإخلاص", "Al-Ikhlas", "The Sincerity", 4, 30, RevelationType.MECCAN, 604),
    SurahMeta(113, "الفلق", "Al-Falaq", "The Daybreak", 5, 30, RevelationType.MECCAN, 604),
    SurahMeta(114, "الناس", "An-Nas", "Mankind", 6, 30, RevelationType.MECCAN, 604)
)
